### ISSUE TITLE
cloud-provider-openstack-acceptance-test-flexvolume-cinder job failed

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#112]
cloud-provider-openstack-acceptance-test-flexvolume-cinder job failed for more than 2 weeks. Process broken at devstack config neutron service.

http://status.openlabtesting.org/builds?job_name=cloud-provider-openstack-acceptance-test-flexvolume-cinder

```
2018-11-14 08:51:32.197 | + lib/neutron:configure_neutron:602        :   configure_neutron_new
2018-11-14 08:51:32.200 | + lib/neutron:configure_neutron_new:158    :   sudo install -d -o stack /etc/neutron
2018-11-14 08:51:32.216 | + lib/neutron:configure_neutron_new:160    :   cd /opt/stack/new/neutron
2018-11-14 08:51:32.219 | + lib/neutron:configure_neutron_new:160    :   exec ./tools/generate_config_file_samples.sh
2018-11-14 08:51:32.921 | Traceback (most recent call last):
2018-11-14 08:51:32.921 |   File "/usr/local/bin/oslo-config-generator", line 11, in <module>
2018-11-14 08:51:32.921 |     sys.exit(main())
2018-11-14 08:51:32.921 |   File "/usr/local/lib/python2.7/dist-packages/oslo_config/generator.py", line 783, in main
2018-11-14 08:51:32.921 |     generate(conf)
2018-11-14 08:51:32.921 |   File "/usr/local/lib/python2.7/dist-packages/oslo_config/generator.py", line 744, in generate
2018-11-14 08:51:32.921 |     groups = _get_groups(_list_opts(conf.namespace))
2018-11-14 08:51:32.921 |   File "/usr/local/lib/python2.7/dist-packages/oslo_config/generator.py", line 484, in _list_opts
2018-11-14 08:51:32.921 |     loaders = _get_raw_opts_loaders(namespaces)
2018-11-14 08:51:32.921 |   File "/usr/local/lib/python2.7/dist-packages/oslo_config/generator.py", line 428, in _get_raw_opts_loaders
2018-11-14 08:51:32.921 |     invoke_on_load=False)
2018-11-14 08:51:32.921 |   File "/usr/local/lib/python2.7/dist-packages/stevedore/named.py", line 81, in __init__
2018-11-14 08:51:32.921 |     verify_requirements)
2018-11-14 08:51:32.921 |   File "/usr/local/lib/python2.7/dist-packages/stevedore/extension.py", line 203, in _load_plugins
2018-11-14 08:51:32.921 |     self._on_load_failure_callback(self, ep, err)
2018-11-14 08:51:32.921 |   File "/usr/local/lib/python2.7/dist-packages/stevedore/extension.py", line 195, in _load_plugins
2018-11-14 08:51:32.921 |     verify_requirements,
2018-11-14 08:51:32.921 |   File "/usr/local/lib/python2.7/dist-packages/stevedore/named.py", line 158, in _load_one_plugin
2018-11-14 08:51:32.921 |     verify_requirements,
2018-11-14 08:51:32.921 |   File "/usr/local/lib/python2.7/dist-packages/stevedore/extension.py", line 223, in _load_one_plugin
2018-11-14 08:51:32.922 |     plugin = ep.resolve()
2018-11-14 08:51:32.922 |   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
2018-11-14 08:51:32.934 |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
2018-11-14 08:51:32.934 |   File "/opt/stack/new/neutron/neutron/opts.py", line 24, in <module>
2018-11-14 08:51:32.934 |     import neutron.conf.agent.common
2018-11-14 08:51:32.934 |   File "/opt/stack/new/neutron/neutron/conf/agent/common.py", line 23, in <module>
2018-11-14 08:51:32.934 |     from neutron.common import config
2018-11-14 08:51:32.934 |   File "/opt/stack/new/neutron/neutron/common/config.py", line 28, in <module>
2018-11-14 08:51:32.934 |     from oslo_service import wsgi
2018-11-14 08:51:32.934 |   File "/usr/local/lib/python2.7/dist-packages/oslo_service/wsgi.py", line 29, in <module>
2018-11-14 08:51:32.934 |     from paste import deploy
2018-11-14 08:51:32.934 | ImportError: cannot import name deploy
2018-11-14 08:51:32.982 | + lib/neutron:configure_neutron_new:1      :   exit_trap
2018-11-14 08:51:32.985 | + ./stack.sh:exit_trap:515                 :   local r=1
2018-11-14 08:51:32.988 | ++ ./stack.sh:exit_trap:516                 :   jobs -p
```

http://logs.openlabtesting.org/logs/58/358/935b3587d066df32cfa57103df17f68bd9dd87ef/cloud-provider-openstack-acceptance-test-flexvolume-cinder/cloud-provider-openstack-acceptance-test-flexvolume-cinder/6cf6e9e/logs/devstacklog.txt.gz

**Comment by liu-sheng** [comment]
This issue is caused by https://review.openstack.org/#/c/510660/, and we have a workaround in https://github.com/theopenlab/openlab-zuul-jobs/blob/master/roles/create-devstack-local-conf/tasks/main.yml#L233, now the Bug should have been fixed.

**Comment by kiwik** [comment]
Thank you @liu-sheng
