### ISSUE TITLE
OpenLab CI upgrading at end of Feb

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#190]
- Zuul
- Nodepool

**Comment by liu-sheng** [comment]
when upgrading nodepool to lastet, a problem found:

The `openstacksdk` >= 0.24.0 will perform a different action about compare two `cloud config`, after debuging, the newest version of openstacksdk will convert the `network_endpoint_override` option of clouds.yaml with `/v2.0` postfix.

Related error message
```
2019-02-26 09:28:05,464 ERROR nodepool.CleanupWorker: Exception in CleanupWorker (leaked instance cleanup)
Traceback (most recent call last):
  File "/home/ubuntu/src/git.openstack.org/openstack-infra/nodepool/nodepool/launcher.py", line 643, in _run
    task()
  File "/home/ubuntu/src/git.openstack.org/openstack-infra/nodepool/nodepool/launcher.py", line 508, in _cleanupLeakedInstances
    manager.cleanupLeakedResources()
  File "/home/ubuntu/src/git.openstack.org/openstack-infra/nodepool/nodepool/driver/openstack/provider.py", line 584, in cleanupLeakedResources
    self.cleanupLeakedPorts()
  File "/home/ubuntu/src/git.openstack.org/openstack-infra/nodepool/nodepool/driver/openstack/provider.py", line 543, in cleanupLeakedPorts
    ports = self.listPorts(status='DOWN')
  File "/home/ubuntu/src/git.openstack.org/openstack-infra/nodepool/nodepool/driver/openstack/provider.py", line 445, in listPorts
    ports = self._client.list_ports(filters={'status': status})
  File "/usr/local/lib/python3.5/dist-packages/openstack/cloud/openstackcloud.py", line 1705, in list_ports
    return self._list_ports(filters)
  File "/usr/local/lib/python3.5/dist-packages/openstack/cloud/openstackcloud.py", line 1729, in _list_ports
    resp = self.network.get("/ports.json", params=filters)
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/adapter.py", line 351, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/openstack/_adapter.py", line 147, in request
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/openstack/task_manager.py", line 219, in submit_function
    return self.submit_task(task)
  File "/usr/local/lib/python3.5/dist-packages/openstack/task_manager.py", line 185, in submit_task
    name=self.name))
openstack.exceptions.TaskManagerStopped: TaskManager otcallinone is no longer running
```

**Comment by liu-sheng** [comment]
done
