### ISSUE TITLE
Manageiq jobs failed when execute 'bundle exec rake db:setup'

### ISSUE THREAD

**Issue by huangtianhua** [theopenlab/openlab#246]
Thank you for reporting bug!

### Describe the bug
Manageiq jobs failed when execute 'bundle exec rake db:setup'

### Related Job information
If the bug is related a CI job, put the job information below:
* job name: manageiq-providers-openstack-test-devstack-master
* job build log link: https://logs.openlabtesting.org/logs/periodic-10/22/github.com/manageiq/manageiq-providers-openstack/master/manageiq-providers-openstack-test-devstack-master/b272de1/job-output.txt.gz
* error log piece: 
2019-04-24 22:58:52.709924 | ubuntu-xenial | + bundle exec rake db:setup
2019-04-24 22:59:04.907476 | ubuntu-xenial | Database 'vmdb_test' already exists
2019-04-24 22:59:09.140427 | ubuntu-xenial | /home/zuul/src/github.com/manageiq/manageiq-providers-openstack/spec/manageiq/db/schema.rb:1182: warning: key :comment is duplicated and overwritten on line 1182
2019-04-24 22:59:09.190862 | ubuntu-xenial | /home/zuul/src/github.com/manageiq/manageiq-providers-openstack/spec/manageiq/db/schema.rb:5882: warning: key :comment is duplicated and overwritten on line 5882
2019-04-24 22:59:09.196476 | ubuntu-xenial | /home/zuul/src/github.com/manageiq/manageiq-providers-openstack/spec/manageiq/db/schema.rb:7345: warning: key :comment is duplicated and overwritten on line 7345
2019-04-24 22:59:09.231879 | ubuntu-xenial | The version of PostgreSQL being connected to is incompatible with ManageIQ (10 required)
2019-04-24 22:59:09.232813 | ubuntu-xenial | NOTICE:  extension "plpgsql" already exists, skipping
2019-04-24 22:59:23.070257 | ubuntu-xenial | Created database 'vmdb_development'
2019-04-24 22:59:23.070483 | ubuntu-xenial | ** Using session_store: ActionDispatch::Session::MemCacheStore
2019-04-24 22:59:23.070562 | ubuntu-xenial | ** ManageIQ master, codename: Ivanchuk
2019-04-24 22:59:23.070617 | ubuntu-xenial | -- enable_extension("plpgsql")
2019-04-24 22:59:23.070651 | ubuntu-xenial |    -> 0.0222s
2019-04-24 22:59:23.070743 | ubuntu-xenial | -- create_table("accounts", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.070776 | ubuntu-xenial |    -> 0.1644s
2019-04-24 22:59:23.070877 | ubuntu-xenial | -- create_table("advanced_settings", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.070911 | ubuntu-xenial |    -> 0.1807s
2019-04-24 22:59:23.071008 | ubuntu-xenial | -- create_table("asset_details", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.071041 | ubuntu-xenial |    -> 0.0410s
2019-04-24 22:59:23.071147 | ubuntu-xenial | -- create_table("assigned_server_roles", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.071181 | ubuntu-xenial |    -> 0.0769s
2019-04-24 22:59:23.071276 | ubuntu-xenial | -- create_table("audit_events", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.071309 | ubuntu-xenial |    -> 0.2460s
2019-04-24 22:59:23.071438 | ubuntu-xenial | -- create_table("authentication_configuration_script_bases", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.071520 | ubuntu-xenial |    -> 0.0276s
2019-04-24 22:59:23.071645 | ubuntu-xenial | -- create_table("authentication_orchestration_stacks", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.071679 | ubuntu-xenial |    -> 0.0287s
2019-04-24 22:59:23.071779 | ubuntu-xenial | -- create_table("authentications", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.071812 | ubuntu-xenial |    -> 0.0746s
2019-04-24 22:59:23.071915 | ubuntu-xenial | -- create_table("automate_workspaces", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.071949 | ubuntu-xenial |    -> 0.0301s
2019-04-24 22:59:23.072052 | ubuntu-xenial | -- create_table("availability_zones", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.072086 | ubuntu-xenial |    -> 0.0573s
2019-04-24 22:59:23.072187 | ubuntu-xenial | -- create_table("binary_blob_parts", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.072221 | ubuntu-xenial |    -> 0.2026s
2019-04-24 22:59:23.072316 | ubuntu-xenial | -- create_table("binary_blobs", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.072349 | ubuntu-xenial |    -> 0.2592s
2019-04-24 22:59:23.072451 | ubuntu-xenial | -- create_table("blacklisted_events", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.072485 | ubuntu-xenial |    -> 0.4993s
2019-04-24 22:59:23.072587 | ubuntu-xenial | -- create_table("bottleneck_events", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.072620 | ubuntu-xenial |    -> 0.0715s
2019-04-24 22:59:23.072713 | ubuntu-xenial | -- create_table("canisters", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.072746 | ubuntu-xenial |    -> 0.0341s
2019-04-24 22:59:23.072847 | ubuntu-xenial | -- create_table("chargeable_fields", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.072881 | ubuntu-xenial |    -> 0.0236s
2019-04-24 22:59:23.073000 | ubuntu-xenial | -- create_table("chargeback_rate_detail_currencies", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.073035 | ubuntu-xenial |    -> 0.1253s
2019-04-24 22:59:23.073152 | ubuntu-xenial | -- create_table("chargeback_rate_detail_measures", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.073192 | ubuntu-xenial |    -> 0.0254s
2019-04-24 22:59:23.073313 | ubuntu-xenial | -- create_table("chargeback_rate_details", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.073350 | ubuntu-xenial |    -> 0.0479s
2019-04-24 22:59:23.073451 | ubuntu-xenial | -- create_table("chargeback_rates", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.073484 | ubuntu-xenial |    -> 0.0350s
2019-04-24 22:59:23.073584 | ubuntu-xenial | -- create_table("chargeback_tiers", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.073634 | ubuntu-xenial |    -> 0.0155s
2019-04-24 22:59:23.073736 | ubuntu-xenial | -- create_table("classifications", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.073784 | ubuntu-xenial |    -> 0.2275s
2019-04-24 22:59:23.073894 | ubuntu-xenial | -- create_table("cloud_database_flavors", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.073928 | ubuntu-xenial |    -> 0.6068s
2019-04-24 22:59:23.074026 | ubuntu-xenial | -- create_table("cloud_databases", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.074059 | ubuntu-xenial |    -> 0.4624s
2019-04-24 22:59:23.074156 | ubuntu-xenial | -- create_table("cloud_networks", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.074189 | ubuntu-xenial |    -> 0.1549s
2019-04-24 22:59:23.074303 | ubuntu-xenial | -- create_table("cloud_object_store_containers", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.074367 | ubuntu-xenial |    -> 0.0811s
2019-04-24 22:59:23.074483 | ubuntu-xenial | -- create_table("cloud_object_store_objects", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.074516 | ubuntu-xenial |    -> 0.0529s
2019-04-24 22:59:23.074629 | ubuntu-xenial | -- create_table("cloud_resource_quotas", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.074663 | ubuntu-xenial |    -> 0.2218s
2019-04-24 22:59:23.074770 | ubuntu-xenial | -- create_table("cloud_services", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.074798 | ubuntu-xenial |    -> 0.2875s
2019-04-24 22:59:23.074881 | ubuntu-xenial | -- create_table("cloud_subnets", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.074909 | ubuntu-xenial |    -> 0.2030s
2019-04-24 22:59:23.075005 | ubuntu-xenial | -- create_table("cloud_subnets_network_ports", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.075034 | ubuntu-xenial |    -> 0.2332s
2019-04-24 22:59:23.075123 | ubuntu-xenial | -- create_table("cloud_tenant_flavors", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.075152 | ubuntu-xenial |    -> 0.0354s
2019-04-24 22:59:23.075234 | ubuntu-xenial | -- create_table("cloud_tenants", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.075262 | ubuntu-xenial |    -> 0.0554s
2019-04-24 22:59:23.075349 | ubuntu-xenial | -- create_table("cloud_tenants_vms", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.075377 | ubuntu-xenial |    -> 0.1256s
2019-04-24 22:59:23.075481 | ubuntu-xenial | -- create_table("cloud_volume_backups", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.075515 | ubuntu-xenial |    -> 0.0762s
2019-04-24 22:59:23.075607 | ubuntu-xenial | -- create_table("cloud_volume_snapshots", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.075635 | ubuntu-xenial |    -> 0.3895s
2019-04-24 22:59:23.075722 | ubuntu-xenial | -- create_table("cloud_volume_types", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.075751 | ubuntu-xenial |    -> 0.1825s
2019-04-24 22:59:23.075834 | ubuntu-xenial | -- create_table("cloud_volumes", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.075862 | ubuntu-xenial |    -> 0.3377s
2019-04-24 22:59:23.075950 | ubuntu-xenial | -- create_table("compliance_details", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.075979 | ubuntu-xenial |    -> 0.0822s
2019-04-24 22:59:23.076059 | ubuntu-xenial | -- create_table("compliances", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.076087 | ubuntu-xenial |    -> 0.0739s
2019-04-24 22:59:23.076173 | ubuntu-xenial | -- create_table("computer_systems", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.076201 | ubuntu-xenial |    -> 0.1297s
2019-04-24 22:59:23.076281 | ubuntu-xenial | -- create_table("conditions", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.076309 | ubuntu-xenial |    -> 0.0519s
2019-04-24 22:59:23.076402 | ubuntu-xenial | -- create_table("conditions_miq_policies", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.076430 | ubuntu-xenial |    -> 0.0148s
2019-04-24 22:59:23.076524 | ubuntu-xenial | -- create_table("configuration_locations", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.076552 | ubuntu-xenial |    -> 0.1916s
2019-04-24 22:59:23.076667 | ubuntu-xenial | -- create_table("configuration_locations_configuration_profiles", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.076698 | ubuntu-xenial |    -> 0.1557s
2019-04-24 22:59:23.076795 | ubuntu-xenial | -- create_table("configuration_organizations", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.076823 | ubuntu-xenial |    -> 0.2512s
2019-04-24 22:59:23.076944 | ubuntu-xenial | -- create_table("configuration_organizations_configuration_profiles", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.076972 | ubuntu-xenial |    -> 0.0457s
2019-04-24 22:59:23.077063 | ubuntu-xenial | -- create_table("configuration_profiles", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:23.077100 | ubuntu-xenial |    -> 0.2052s
......
2019-04-24 22:59:23.081732 | ubuntu-xenial |    -> 0.3791s
2019-04-24 22:59:23.081818 | ubuntu-xenial | -- create_table("database_backups", {:id=>:bigserial, :force=>:cascade})
2019-04-24 22:59:35.343039 | ubuntu-xenial |    -> 0.0242srake aborted!
2019-04-24 22:59:35.343211 | ubuntu-xenial | ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "metric_rollups_base_id_seq" does not exist
2019-04-24 22:59:35.345659 | ubuntu-xenial | : CREATE TABLE "metric_rollups_01" ("id" bigint DEFAULT nextval('metric_rollups_base_id_seq'::regclass) PRIMARY KEY, "timestamp" timestamp, "capture_interval" integer, "resource_type" character varying, "resource_id" bigint, "cpu_usage_rate_average" float, "cpu_usagemhz_rate_average" float, "mem_usage_absolute_average" float, "disk_usage_rate_average" float, "net_usage_rate_average" float, "sys_uptime_absolute_latest" float, "created_on" timestamp, "derived_cpu_available" float, "derived_memory_available" float, "derived_memory_used" float, "derived_cpu_reserved" float, "derived_memory_reserved" float, "derived_vm_count_on" integer, "derived_host_count_on" integer, "derived_vm_count_off" integer, "derived_host_count_off" integer, "derived_storage_total" float, "derived_storage_free" float, "capture_interval_name" character varying, "assoc_ids" text, "cpu_ready_delta_summation" float, "cpu_system_delta_summation" float, "cpu_wait_delta_summation" float, "resource_name" character varying, "cpu_used_delta_summation" float, "tag_names" text, "parent_host_id" bigint, "parent_ems_cluster_id" bigint, "parent_storage_id" bigint, "parent_ems_id" bigint, "derived_storage_vm_count_registered" float, "derived_storage_vm_count_unregistered" float, "derived_storage_vm_count_unmanaged" float, "derived_storage_used_registered" float, "derived_storage_used_unregistered" float, "derived_storage_used_unmanaged" float, "derived_storage_snapshot_registered" float, "derived_storage_snapshot_unregistered" float, "derived_storage_snapshot_unmanaged" float, "derived_storage_mem_registered" float, "derived_storage_mem_unregistered" float, "derived_storage_mem_unmanaged" float, "derived_storage_disk_registered" float, "derived_storage_disk_unregistered" float, "derived_storage_disk_unmanaged" float, "derived_storage_vm_count_managed" float, "derived_storage_used_managed" float, "derived_storage_snapshot_managed" float, "derived_storage_mem_managed" float, "derived_storage_disk_managed" float, "min_max" text, "intervals_in_rollup" integer, "mem_vmmemctl_absolute_average" float, "mem_vmmemctltarget_absolute_average" float, "mem_swapin_absolute_average" float, "mem_swapout_absolute_average" float, "mem_swapped_absolute_average" float, "mem_swaptarget_absolute_average" float, "disk_devicelatency_absolute_average" float, "disk_kernellatency_absolute_average" float, "disk_queuelatency_absolute_average" float, "derived_vm_used_disk_storage" float, "derived_vm_allocated_disk_storage" float, "derived_vm_numvcpus" float, "time_profile_id" bigint, "derived_host_sockets" integer, "derived_host_count_total" integer, "derived_vm_count_total" integer, "stat_container_group_create_rate" integer, "stat_container_group_delete_rate" integer, "stat_container_image_registration_rate" integer)
2019-04-24 22:59:35.345817 | ubuntu-xenial | /home/zuul/src/github.com/manageiq/manageiq-providers-openstack/spec/manageiq/db/schema.rb:2165:in `block in <top (required)>'
2019-04-24 22:59:35.345938 | ubuntu-xenial | /home/zuul/src/github.com/manageiq/manageiq-providers-openstack/spec/manageiq/db/schema.rb:13:in `<top (required)>'
2019-04-24 22:59:35.346003 | ubuntu-xenial | /root/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
2019-04-24 22:59:35.346064 | ubuntu-xenial | /root/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
2019-04-24 22:59:35.346147 | ubuntu-xenial | PG::UndefinedTable: ERROR:  relation "metric_rollups_base_id_seq" does not exist
2019-04-24 22:59:35.346271 | ubuntu-xenial | /home/zuul/src/github.com/manageiq/manageiq-providers-openstack/spec/manageiq/db/schema.rb:2165:in `block in <top (required)>'
2019-04-24 22:59:35.346430 | ubuntu-xenial | /home/zuul/src/github.com/manageiq/manageiq-providers-openstack/spec/manageiq/db/schema.rb:13:in `<top (required)>'
2019-04-24 22:59:35.346518 | ubuntu-xenial | /root/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
2019-04-24 22:59:35.346582 | ubuntu-xenial | /root/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
2019-04-24 22:59:35.346623 | ubuntu-xenial | Tasks: TOP => db:schema:load
2019-04-24 22:59:35.346676 | ubuntu-xenial | (See full trace by running task with --trace)

### Steps to reproduce the issue
Describe how to reproduce the issue:

**Comment by h00130372** [comment]
I opened a issue in manageiq, see below:
https://github.com/ManageIQ/manageiq-providers-openstack/issues/464

**Comment by h00130372** [comment]
These days another error raised, see the log: 
https://logs.openlabtesting.org/logs/periodic-10/22/github.com/manageiq/manageiq-providers-openstack/master/manageiq-providers-openstack-test-devstack-master/c3d21ff/job-output.txt.gz

2019-05-05 10:56:43.131008 | ubuntu-xenial | Gem::InstallError: dry-validation requires Ruby version >= 2.4.0.
2019-05-05 10:56:43.131196 | ubuntu-xenial | An error occurred while installing dry-validation (0.13.1), and Bundler cannot
2019-05-05 10:56:43.131236 | ubuntu-xenial | continue.
2019-05-05 10:56:43.131339 | ubuntu-xenial | Make sure that `gem install dry-validation -v '0.13.1' --source
2019-05-05 10:56:43.131416 | ubuntu-xenial | 'https://rubygems.org/'` succeeds before bundling.
2019-05-05 10:56:43.131433 | ubuntu-xenial |
2019-05-05 10:56:43.131465 | ubuntu-xenial | In Gemfile:
2019-05-05 10:56:43.131553 | ubuntu-xenial |   manageiq-api was resolved to 4.1.0.pre.pre, which depends on
2019-05-05 10:56:43.131628 | ubuntu-xenial |     config was resolved to 1.6.1, which depends on
2019-05-05 10:56:43.131668 | ubuntu-xenial |       dry-validation
2019-05-05 10:56:43.318161 | ubuntu-xenial |
2019-05-05 10:56:43.318507 | ubuntu-xenial | == Command ["bundle update --jobs=3"] failed in /home/zuul/src/github.com/manageiq/manageiq-providers-openstack ==
2019-05-05 10:56:43.484930 | ubuntu-xenial | ERROR
2019-05-05 10:56:43.485259 | ubuntu-xenial | {
2019-05-05 10:56:43.485362 | ubuntu-xenial |   "delta": "0:08:57.268005",
2019-05-05 10:56:43.485456 | ubuntu-xenial |   "end": "2019-05-05 10:56:43.324296",
2019-05-05 10:56:43.485547 | ubuntu-xenial |   "msg": "non-zero return code",
2019-05-05 10:56:43.485651 | ubuntu-xenial |   "rc": 1,
2019-05-05 10:56:43.485741 | ubuntu-xenial |   "start": "2019-05-05 10:47:46.056291"
2019-05-05 10:56:43.485829 | ubuntu-xenial | }


seems we have to use ruby >= 2.4.0.

**Comment by kiwik** [comment]
@h00130372 thank you to report this issue.

**Comment by huangtianhua** [comment]
Manageiq requires postgresql version 10. See job
log details:
https://logs.openlabtesting.org/logs/periodic-10/22/github.com/manageiq/manageiq-providers-openstack/master/manageiq-providers-openstack-test-devstack-master/bd94d1d/job-output.txt.gz

"The version of PostgreSQL being connected to is incompatible with ManageIQ (10 required)"

**Comment by kiwik** [comment]
Related PRs have been merged, close this issue.

**Comment by huangtianhua** [comment]
@kiwik The jobs are still failed, these two prs only fix some problems of this issue, I have transfer this to @Yikun and he will continue to work on it.

**Comment by kiwik** [comment]
@huangtianhua thank you clarification, let's to continue to trace the issue.
