### ISSUE TITLE
Server can't be operated in Vexxhost Cloud

### ISSUE THREAD

**Issue by bzhaoopenstack** [theopenlab/openlab#347]
Openlab CI nodepool can not operate the servers/resources in Vexxhost Cloud, it failed with 401 when we use the original account to access the cloud services with openstack client.
```
- export OS_CLOUD=vexxhost
- openstack_ server list
The request you have made requires authentication. (HTTP 401) (Request-ID: req-cc17cab3-0ae4-4529-a6d8-f8cbf597340e)
```

Nodepool log:
```
2019-08-27 01:28:36,792 DEBUG nodepool.DeletedNodeWorker: Marking for deletion unlocked node 0000030242 (state: deleting, allocated_to: None)
2019-08-27 01:28:36,792 INFO nodepool.DeletedNodeWorker: Deleting deleting instance 88b3daee-a562-4558-9359-95b16ef27110 from vexxhost-openlab
2019-08-27 01:28:37,249 ERROR nodepool.NodeDeleter: Exception deleting instance 88b3daee-a562-4558-9359-95b16ef27110 from vexxhost-openlab:
Traceback (most recent call last):
  File "/opt/src/nodepool/nodepool/launcher.py", line 79, in delete
    manager.cleanupNode(node.external_id)
  File "/opt/src/nodepool/nodepool/driver/openstack/provider.py", line 470, in cleanupNode
    server = self.getServer(server_id)
  File "/opt/src/nodepool/nodepool/driver/openstack/provider.py", line 360, in getServer
    return self._client.get_server(server_id)
  File "/usr/local/lib/python3.5/dist-packages/openstack/cloud/openstackcloud.py", line 3135, in get_server
    server = _utils._get_entity(self, searchfunc, name_or_id, filters)
  File "/usr/local/lib/python3.5/dist-packages/openstack/cloud/_utils.py", line 205, in _get_entity
    entities = search(name_or_id, filters, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/openstack/cloud/openstackcloud.py", line 1574, in search_servers
    detailed=detailed, all_projects=all_projects, bare=bare)
  File "/usr/local/lib/python3.5/dist-packages/openstack/cloud/openstackcloud.py", line 2126, in list_servers
    bare=bare)
  File "/usr/local/lib/python3.5/dist-packages/openstack/cloud/openstackcloud.py", line 2144, in _list_servers
    all_projects=all_projects, **filters)]
  File "/usr/local/lib/python3.5/dist-packages/openstack/cloud/openstackcloud.py", line 2142, in <listcomp>
    self._normalize_server(server._to_munch())
  File "/usr/local/lib/python3.5/dist-packages/openstack/resource.py", line 1350, in list
    microversion=microversion)
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/adapter.py", line 375, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/openstack/_adapter.py", line 124, in request
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/adapter.py", line 237, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/session.py", line 704, in request
    auth_headers = self.get_auth_headers(auth)
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/session.py", line 1097, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/plugin.py", line 95, in get_headers
    token = self.get_token(session)
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/identity/base.py", line 88, in get_token
    return self.get_access(session).auth_token
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/identity/base.py", line 134, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/identity/generic/base.py", line 208, in get_auth_ref
    return self._plugin.get_auth_ref(session, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/identity/v3/base.py", line 178, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/session.py", line 1045, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/session.py", line 890, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-83085163-db74-407a-ab1f-e6fa9cd7a1c7)
```

I try to login through [vexxhost login page](https://secure.vexxhost.com/billing/clientarea.php) with our account, and found a paylist which is end up in 18/08/2019, so I guess our account must be hang by this paylist.

Wish you guys could help to see what happened, thank you very much

**Comment by bzhaoopenstack** [comment]
@mnaser @mrhillsman 
Melvin, Could you please help to contact mnaser? I can't find his github account.. But I already sent out an email to you guys, not get reply yet.. ;-).

Thank you.

**Comment by Ansuhree** [comment]
Hi ZhaoBo,

I am Anushree from Click2Cloud Inc. We can help you out. Please reach out to me on- anushree.jain@click2cloud.net

Thank you.

**Comment by bzhaoopenstack** [comment]
Help, anyone can help us for this?? How can we contact mnaser in other way? Melvin, could you please help us?
Thank you.

**Comment by bzhaoopenstack** [comment]
Hi Ansuhree, 
I sent out an email to you. Did you have not see it yet? ;-). Please clear my confused at first.
Hope you can help us.

Thank you very much.

**Comment by bzhaoopenstack** [comment]
So many thanks to Vexxhost to support OpenLab. We have confirmed with Vexxhost that they will quit from OpenLab by a reluctance reason. We are totally understood. Thanks very much to Vexxhost.

**Comment by bzhaoopenstack** [comment]
Hi @Ansuhree ,

Can I still access you by email anushree.jain@click2cloud.net ? ;-).. I sent out an email before, but no reply from you. If possible, could we get help from you side? 

Thanks

**Comment by wangxiyuan** [comment]
Vexxhost has been removed.
