### ISSUE TITLE
Some resources in vexxhost stuck in intermediate state and cannot be deleted

### ISSUE THREAD

**Issue by liu-sheng** [theopenlab/openlab#54]
There are 3 VM in vexxhost used by job running stuck in "deleting" state after job accomplished.
see:
```
root@donotdelete-l002426780:~# openstack server list --long -c Name -c ID -c Status -c "Task State" -c "Networks"
+--------------------------------------+----------------------------------------------------+--------+------------+--------------------------------------+
| ID                                   | Name                                               | Status | Task State | Networks                             |
+--------------------------------------+----------------------------------------------------+--------+------------+--------------------------------------+
| e9662c0b-de31-42b0-865d-e70b7f844afc | ubuntu-xenial-vexxhost-vexxhost-0000004687         | ACTIVE | None       | int-net=192.168.0.17, 162.253.55.62  |
| d162b657-780f-46c0-8b91-ea278937d1cc | ubuntu-xenial-vexxhost-vexxhost-0000004686         | ACTIVE | None       | int-net=192.168.0.43, 162.253.55.174 |
| 8766118b-390a-4ae2-a013-200e343ed8ae | ubuntu-xenial-vexxhost-vexxhost-0000004685         | ACTIVE | None       | int-net=192.168.0.37, 162.253.55.201 |
| 2db67fcd-4d77-4427-ba6e-065f36af6352 | ubuntu-xenial-vexxhost-vexxhost-0000004684         | ACTIVE | None       | int-net=192.168.0.15, 162.253.55.141 |
| 07bdd972-3e36-4f65-9e2a-a79ab2c82d83 | ubuntu-xenial-vexxhost-vexxhost-0000004683         | ACTIVE | None       | int-net=192.168.0.25, 162.253.55.172 |
| 7806d1b0-7c64-4aa0-b35d-7e2cafdced95 | ubuntu-xenial-vexxhost-vexxhost-0000004682         | ACTIVE | None       | int-net=192.168.0.21, 162.253.55.142 |
| 855747f4-4929-46af-b743-9338d109b3b7 | ubuntu-xenial-vexxhost-vexxhost-0000004681         | ACTIVE | None       | int-net=192.168.0.31, 162.253.55.202 |
| 0dd54d07-9ae4-4041-80b2-f863ef213967 | ubuntu-xenial-vexxhost-vexxhost-0000004653         | ACTIVE | deleting   | int-net=192.168.0.41                 |
| 9ad9036c-440d-45ec-b73b-3cf658228216 | ubuntu-xenial-vexxhost-vexxhost-0000004625         | ACTIVE | deleting   | int-net=192.168.0.20                 |
| 84a5681b-9d4f-4311-87bf-49e1bae080cf | ubuntu-xenial-vexxhost-vexxhostallinone-0000001990 | ACTIVE | deleting   | int-net=192.168.0.32                 |
+--------------------------------------+----------------------------------------------------+--------+------------+--------------------------------------+

```
After checking the nodepool-launcher.log, we can find a 500 error when deleting the server, see:
```
2018-04-24 09:45:29,464 ERROR nodepool.NodeDeleter: Exception deleting instance 84a5681b-9d4f-4311-87bf-49e1bae080cf from vexxhostallinone:
Traceback (most recent call last):
  File "/root/nodepool/nodepool/launcher.py", line 79, in delete
    manager.cleanupNode(node.external_id)
  File "/root/nodepool/nodepool/driver/openstack/provider.py", line 513, in cleanupNode
    self.deleteServer(server_id)
  File "/root/nodepool/nodepool/driver/openstack/provider.py", line 505, in deleteServer
    return self._client.delete_server(server_id, delete_ips=True)
  File "/usr/local/lib/python3.5/dist-packages/shade/openstackcloud.py", line 7061, in delete_server
    delete_ip_retry=delete_ip_retry)
  File "/usr/local/lib/python3.5/dist-packages/shade/openstackcloud.py", line 7102, in _delete_server
    error_message="Error in deleting server")
  File "/usr/local/lib/python3.5/dist-packages/keystoneauth1/adapter.py", line 319, in delete
    return self.request(url, 'DELETE', **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/shade/_adapter.py", line 158, in request
    return self._munch_response(response, error_message=error_message)
  File "/usr/local/lib/python3.5/dist-packages/shade/_adapter.py", line 114, in _munch_response
    exc.raise_from_response(response, error_message=error_message)
  File "/usr/local/lib/python3.5/dist-packages/shade/exc.py", line 176, in raise_from_response
    raise OpenStackCloudHTTPError(msg, response=response)
shade.exc.OpenStackCloudHTTPError: Error in deleting server. (500) Server Error for url: https://compute-ca-ymq-1.vexxhost.net/v2.1/servers/84a5681b-9d4f-4311-87bf-49e1bae080cf Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
<type 'exceptions.AttributeError'>

```

Similarly, there are some loadbalancers, ports, volumes resources also cannot be deleted. see:
```
root@donotdelete-l002426780:~# openstack loadbalancer list
+--------------------------------------+----------------------------------+----------------------------------+--------------+---------------------+----------+
| id                                   | name                             | project_id                       | vip_address  | provisioning_status | provider |
+--------------------------------------+----------------------------------+----------------------------------+--------------+---------------------+----------+
| b14b32d2-11bc-49b1-a6ff-5a4c2cba3a6a | a2c2d09c7432a11e88859fa163e1960d | 69b5f56c11e84927abebfdca8039b48b | 192.168.0.31 | PENDING_CREATE      | octavia  |
| ed255e90-9b42-46c8-8224-e85331c4fe56 | a858f0cb0435f11e88bd5fa163e99092 | 69b5f56c11e84927abebfdca8039b48b | 192.168.0.19 | PENDING_CREATE      | octavia  |
| 257b6ad0-574a-422b-a81d-d3bf5191c8ca | a4a90b09547b811e8ad48fa163e34756 | 69b5f56c11e84927abebfdca8039b48b | 192.168.0.30 | ERROR               | octavia  |
| 65a95a36-7d8b-44b4-af17-3fb5b9d795dd | a036dfd0347de11e8b7b1fa163eacbdf | 69b5f56c11e84927abebfdca8039b48b | 192.168.0.28 | ERROR               | octavia  |
| 5553dc12-0307-400b-9d66-6ac61682085e | ad8619095482911e896c3fa163ecffdb | 69b5f56c11e84927abebfdca8039b48b | 192.168.0.40 | ERROR               | octavia  |
+--------------------------------------+----------------------------------+----------------------------------+--------------+---------------------+----------+
root@donotdelete-l002426780:~# openstack port list
+--------------------------------------+---------------------------------------------------+-------------------+-----------------------------------------------------------------------------+--------+
| ID                                   | Name                                              | MAC Address       | Fixed IP Addresses                                                          | Status |
+--------------------------------------+---------------------------------------------------+-------------------+-----------------------------------------------------------------------------+--------+
| 0135ffe3-8e68-4476-bdd7-ed3b125281a1 |                                                   | fa:16:3e:f9:18:d2 | ip_address='192.168.0.41', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| 062d5a27-01c7-4436-a916-04b96afcd1d2 |                                                   | fa:16:3e:5d:1d:38 | ip_address='192.168.0.32', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| 0e8dffaf-b5f6-4a89-af8f-6eb1cf0f24a2 |                                                   | fa:16:3e:1f:e2:49 | ip_address='192.168.0.1', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2'  | ACTIVE |
| 2df7aba0-dd02-4b22-bc5d-c234beb54217 |                                                   | fa:16:3e:45:ff:f8 | ip_address='192.168.0.37', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| 2ed49aeb-884c-48a8-9841-46235ebc3b10 |                                                   | fa:16:3e:28:81:13 | ip_address='192.168.0.43', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| 3509b9ca-a370-4fd0-93d9-aca826b2e2ba |                                                   | fa:16:3e:81:c0:54 | ip_address='192.168.0.31', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| 3d3ddf2a-8f8f-45b1-8d7f-2d78d1408f9c |                                                   | fa:16:3e:34:55:e6 | ip_address='192.168.0.17', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| 4fe24e50-dbe6-4308-a79d-3cbd56bb981e |                                                   | fa:16:3e:67:3f:4f | ip_address='192.168.0.12', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| 5bd23973-9319-4c1e-bad6-9693159a8f29 |                                                   | fa:16:3e:a7:ad:e0 | ip_address='192.168.0.21', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| 70b099d3-69d7-427a-b988-3f32af7397ff |                                                   | fa:16:3e:5e:c5:a0 | ip_address='192.168.0.11', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| 75ff3309-159a-4ef8-ad5a-c2d1e35732d5 |                                                   | fa:16:3e:be:c5:43 | ip_address='192.168.0.25', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| 87cda94e-275c-4bec-96c7-6f4e886be922 |                                                   | fa:16:3e:c7:0d:a7 | ip_address='192.168.0.20', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| a6abe671-a7e1-47c6-9e73-7a3890f65eff | loadbalancer-65a95a36-7d8b-44b4-af17-3fb5b9d795dd | fa:16:3e:dd:cd:26 | ip_address='192.168.0.28', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | DOWN   |
| b8ac7963-91f3-4ea4-8f2b-a7440418b15f |                                                   | fa:16:3e:43:f7:93 | ip_address='192.168.0.10', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
| ce7c581d-81a2-493a-90f3-da62bae35de3 |                                                   | fa:16:3e:0a:2a:89 | ip_address='192.168.0.15', subnet_id='ac8cadce-db65-4581-962d-0beb27586eb2' | ACTIVE |
+--------------------------------------+---------------------------------------------------+-------------------+-----------------------------------------------------------------------------+--------+
root@donotdelete-l002426780:~# openstack volume list
+--------------------------------------+------------------------------------------+----------+------+-------------+
| ID                                   | Name                                     | Status   | Size | Attached to |
+--------------------------------------+------------------------------------------+----------+------+-------------+
| cb2ae4d0-d47e-4a45-9e5f-13d1127f88e3 | pvc-60d0ff7f-432a-11e8-b054-fa163ee8639c | creating |    1 |             |
+--------------------------------------+------------------------------------------+----------+------+-------------+

```

**Comment by liu-sheng** [comment]
Hi @mrhillsman, I have add an issue describing the current problem of vexxhost, please take a look, thanks.

**Comment by mnaser** [comment]
They have all been cleaned up and the deployment has been upgraded to Queens which handles these issues better.

**Comment by mrhillsman** [comment]
@mnaser thanks again for your assistance here. @kiwik @liu-sheng closing, please re-open if necessary.

**Comment by kiwik** [comment]
Thank you @mrhillsman and @mnaser 👍
