### ISSUE TITLE
cluster-api-openstack-provider CI failure

### ISSUE THREAD

**Issue by jichenjc** [theopenlab/openlab#581]
Thank you for reporting bug!

### Describe the bug

https://logs.openlabtesting.org/logs/19/619/1a927b8c51748f4863a975d68db7b577522f9de2/check/cluster-api-provider-openstack-current-acceptance-test-v1.18/b8d9e5c/job-output.txt.gz

```
020-09-02 04:17:04.385339 | ubuntu-bionic-large | Running virtualenv with interpreter /usr/bin/python3.6
2020-09-02 04:17:04.639379 | ubuntu-bionic-large | Traceback (most recent call last):
2020-09-02 04:17:04.639597 | ubuntu-bionic-large |   File "/usr/local/lib/python3.6/dist-packages/virtualenv.py", line 24, in <module>
2020-09-02 04:17:04.639661 | ubuntu-bionic-large |     import distutils.spawn
2020-09-02 04:17:04.639779 | ubuntu-bionic-large |   File "/usr/local/lib/python3.6/dist-packages/_distutils_hack/__init__.py", line 82, in create_module
2020-09-02 04:17:04.645680 | ubuntu-bionic-large |     return importlib.import_module('._distutils', 'setuptools')
2020-09-02 04:17:04.645803 | ubuntu-bionic-large |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-09-02 04:17:04.647137 | ubuntu-bionic-large |     return _bootstrap._gcd_import(name[level:], package, level)
2020-09-02 04:17:04.647219 | ubuntu-bionic-large | ModuleNotFoundError: No module named 'setuptools'
2020-09-02 04:17:04.685334 | ubuntu-bionic-large | ./safe-devstack-vm-gate-wrap.sh: line 518: /tmp/ansible/bin/pip: No such file or directory
2020-09-02 04:17:04.686012 | ubuntu-bionic-large | ./safe-devstack-vm-gate-wrap.sh: line 519: /tmp/ansible/bin/pip: No such file or directory
2020-09-02 04:17:04.689069 | ubuntu-bionic-large | cat: /etc/nodepool/primary_node_private: No such file or directory
2020-09-02 04:17:04.690861 | ubuntu-bionic-large | cat: /etc/nodepool/sub_nodes_private: No such file or directory
2020-09-02 04:17:04.694733 | ubuntu-bionic-large | ./safe-devstack-vm-gate-wrap.sh: line 556: /tmp/ansible/bin/ansible: No such file or directory
2020-09-02 04:17:04.695697 | ubuntu-bionic-large | ./safe-devstack-vm-gate-wrap.sh: line 558: /tmp/ansible/bin/ansible: No such file or directory
2020-09-02 04:17:04.696579 | ubuntu-bionic-large | ./safe-devstack-vm-gate-wrap.sh: line 562: /tmp/ansible/bin/ansible: No such file or directory
2020-09-02 04:17:04.697423 | ubuntu-bionic-large | ./safe-devstack-vm-gate-wrap.sh: line 564: /tmp/ansible/bin/ansible: No such file or directory
2020-09-02 04:17:04.707647 | ubuntu-bionic-large | /home/zuul/workspace/devstack-gate/functions.sh: line 172: warning: command substitution: ignored null byte in input
2020-09-02 04:17:04.719614 | ubuntu-bionic-large | Setting up the hosts
2020-09-02 04:17:04.719789 | ubuntu-bionic-large | ... this takes a few seconds (logs at logs/devstack-gate-setup-host.txt.gz)
2020-09-02 04:17:04.721337 | ubuntu-bionic-large | ./safe-devstack-vm-gate-wrap.sh: line 578: /tmp/ansible/bin/ara: No such file or directory
2020-09-02 04:17:04.722594 | ubuntu-bionic-large | gzip: /home/zuul/workspace/logs/ara: No such file or directory
2020-09-02 04:17:04.722769 | ubuntu-bionic-large | *** FAILED with status: 127
2020-09-02 04:17:14.958014 | ubuntu-bionic-large | ERROR
2020-09-02 04:17:14.958502 | ubuntu-bionic-large | {
2020-09-02 04:17:14.958609 | ubuntu-bionic-large |   "delta": "0:00:05.828767",
2020-09-02 04:17:14.958701 | ubuntu-bionic-large |   "end": "2020-09-02 04:17:04.723643",
2020-09-02 04:17:14.958806 | ubuntu-bionic-large |   "msg": "non-zero return code",
2020-09-02 04:17:14.958906 | ubuntu-bionic-large |   "rc": 127,
2020-09-02 04:17:14.959017 | ubuntu-bionic-large |   "start": "2020-09-02 04:16:58.894876"
2020-09-02 04:17:14.959127 | ubuntu-bionic-large | }
```

**Comment by jichenjc** [comment]
@wangxiyuan this is 100% failure, can you help to check? thanks

**Comment by wangxiyuan** [comment]
as I know, setuptools recently released new version and have a lot of unknown bugs. And the error here comes from devstack official script. So how about waiting more? If it's not solved, we may add some hack ways later.

**Comment by jichenjc** [comment]
@wangxiyuan thanks, then let's wait for a few days on this , thanks

**Comment by seanschneeweiss** [comment]
A partial workaround was commited https://github.com/openstack/devstack/commit/18b4251bf4f689923a19bf7fbc50d5c2ea422b21 (https://review.opendev.org/#/c/748957/).
But nevertheless, a fix for [`devstack-gate/devstack-vm-gate-wrap.sh`](https://github.com/openstack/devstack-gate/blob/master/devstack-vm-gate-wrap.sh#L513) is still missing.
Could use `export SETUPTOOLS_USE_DISTUTILS=stdlib` before calling `$PIP install` as a workaround (inside [`devstack-gate/devstack-vm-gate-wrap.sh`](https://github.com/openstack/devstack-gate/blob/master/devstack-vm-gate-wrap.sh#L513)) or add it inside the `cmd` section here:  [`install-devstack` zuul-job](https://github.com/theopenlab/openlab-zuul-jobs/blob/d1be443708ac21ab6862e729011f0a9c5ac25f30/roles/install-devstack/tasks/main.yml#L56-L62)

**Comment by jichenjc** [comment]
@seanschneeweiss thanks ~ 
@wangxiyuan I think it's inside CI scope ? or need cluster-api-openstack-proivder do something?

**Comment by wangxiyuan** [comment]
@seanschneeweiss  Thanks for the debug. Yes, export SETUPTOOLS_USE_DISTUTILS can solve the problem. 

And I just saw a new patch that fixed the issue https://github.com/pypa/setuptools/commit/c0085e87c69629ec3cf24dfce887c0fb93fa80dd

So I guess once setuptools release a newer version, the problem will be solved.

We can wait more, or feel free to push the fixing PR to openlab-zuul-job if you can't wait.

**Comment by seanschneeweiss** [comment]
The issue was fixed imho.
